server:
  port: 5004
application:
  url: //:phones.infocomparison.com
  queryServiceName: query-phones
  queryServiceUrl: http://localhost:5003
eureka:
  client:
    enabled: true
    service-url:
       defaultZone: http://localhost:5005/eureka/
